#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ImagePlayground.Resource", IsApplication=true)]

namespace ImagePlayground
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int labelPosition = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int showText = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int circle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int launcher = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040009
			public const int btnCamera = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int button1 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int button2 = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int button3 = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int button4 = 2130968590;
			
			// aapt resource value: 0x7f040002
			public const int cameraPreview = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int customView = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int editText1 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int editText2 = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int left = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int linearLayout1 = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int linearLayout2 = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int relativeLayout1 = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int right = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int textView1 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int textView2 = 2130968581;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CameraEnhanced = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CameraRect = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DraggableRect = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ResizableRect = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PieChart = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int PieChart_labelPosition = 1;
			
			// aapt resource value: 0
			public const int PieChart_showText = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
